
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hymhdfllxtzngzgxedce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5bWhkZmxseHR6bmd6Z3hlZGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNzA1MDksImV4cCI6MjA1Njk0NjUwOX0.XWyPdCxOqEO43SBKOmOMJoD7KZsF5HBwWnLSBAM4tjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
